
language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install: []

install: 
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt

script:
  - make lint
  - make test
